### ISSUE TITLE
Coding videos -- test data

### ISSUE THREAD

**Issue by ib00** [madmann91/fu#1]
I enjoyed your first video on lexing. Good tutorial and easy to follow code so far.
Thanks for doing this.

Just a suggestion: it would be nice to have some test cases (for lexing, parsing, etc.).

**Comment by madmann91** [comment]
Working on it! Still developing the parser at the moment. I will update the project when I have them.

**Comment by ib00** [comment]
Thanks!

One other tutorial/video that I would really like to see is on pattern matching (and how to implement it).
It's something that you never see and it's never discussed in any compiler class.

**Comment by madmann91** [comment]
I've written some documentation on the pattern matching code generator of another compiler project I've worked on. Here's a link: https://github.com/AnyDSL/artic/blob/master/doc/pattern_matching.md. That may or may not help, but it contains the references you need to have a look at pattern matching (it's mostly based on L. Maranget's article). Unfortunately, in the video series, I'm very far from the code generation part at the moment, so that'll have to wait a bit, sadly.

**Comment by asmwarrior** [comment]
> 

Where is the author's video tutorial? Can you share the links? Thanks.

**Comment by madmann91** [comment]
I've started a series of videos on the topic of Compiler Design [here](https://www.youtube.com/channel/UCBFJ3wD3qNSlZ4MqOA9KntA) (the link is also on the README of the `devel` branch, which I am updating in tandem with the videos). I can't code everything and record all of it, that would be too annoying, so I try to focus on one topic at a time.

**Comment by asmwarrior** [comment]
OK, thanks for the info. I see it now. It's in the `devel` branch. (Not the default `master` branch when I open the github page)

**Comment by madmann91** [comment]
I have added tests to the repository (see commit a545df48a874a597abc151f96c709212e05d34ef). It's very basic, but will be improved over time, as I add more features.
