### ISSUE TITLE
Adding macros?

### ISSUE THREAD

**Issue by ib00** [madmann91/fu#2]
Compiler beginner here. I am really enjoying your videos and this project.
Learning a lot.

As a challenge (and similar to you adding attributes to the parser in the video), I
am considering adding simple macros/metaprogramming to the language
(so adding quote/escape, maybe other things are needed).

I've looked at Rust and how deal with macros, but it's a bit over my head at the moment.

Do you have any suggestions how to start? Define the grammar for macros?

Thanks!

**Comment by madmann91** [comment]
For macros I'd recommend having a look at "Hygienic macros", which are macros that are preserving scopes (similar to what Rust does). The general idea behind hygienic macros is that they capture the AST or syntax that is given to them, not just a sequence of tokens, which means that you can modify the syntax while preserving the structure of the program. To implement that, you need to have a parser for those macros, of course, and for that you need to specify syntax that allows those macros to transform the syntax that they are given (some form of pattern matching on AST nodes). Then once you have macros implemented like that, you can just execute them on the fly after parsing, and right before name binding/type-checking.

**Comment by ib00** [comment]
Thanks.

So, you need a way to manipulate AST and carry copy of the environment around?

When you say 'execute them on the fly', that would mean you need some sort of virtual machine
(or codegen) that allows you to evaluate AST after the first compile pass, right?

**Comment by madmann91** [comment]
Think of it as just a set of rules to transform the AST, except the rules are user-written. For hygienic macros, you don't really need a virtual machine, all you need to know is the list of [free variables](https://en.wikipedia.org/wiki/Lambda_calculus#Free_and_bound_variables) (i.e. the variables and symbols that are visible where the macro is invoked), so that you don't create new names that clash with those.

Once you have that, "executing" a macro is basically just replacing the left-hand side of the macro by the right-hand side, where you substitute parameters with the actual arguments passed to the macro (in [lambda calculus](https://en.wikipedia.org/wiki/Lambda_calculus) terms, it would be called [beta-reduction](https://en.wikipedia.org/wiki/Lambda_calculus#%CE%B2-reduction)). I have to admit I have never implemented such a system myself, I am only speaking from what I've read and learnt in PL (Programming Languages) research articles and books.

I recommend going to the [Programming Languages Discord](https://discord.gg/4Kjt3ZE), it's a very warm community with a lot of people that could help you if you need information on how to implement programming languages in general. I cannot really keep this thread up, as it is not really an issue with the project, so I am going to close it. If you want to ask another question on general PL design or continue this discussion, you can reach me through the above-mentioned Discord server.
